// <auto-generated />
using System;
using Exercice_API_01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercice_API_01.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exercice_API_01.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("First_name")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Last_name")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1999, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rémi",
                            Gender = "Homme",
                            LastName = "Debruyne",
                            Password = "sqdgge786dFNYUEI"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1983, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Manu",
                            Gender = "Homme",
                            LastName = "Max",
                            Password = "bhqdpgre2452uigpzesdfe"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(325, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jean",
                            Gender = "Robot",
                            LastName = "Bon",
                            Password = "fghqriuopfghE452HOFUR5Y8UHGHVV"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(122, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jaina",
                            Gender = "Femme",
                            LastName = "Portvaillant",
                            Password = "fkggAZEq451g4r1g4sq"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
